apiVersion: apps/v1
kind: Deployment
metadata:
  name: bccmusic-frontend
  namespace: default
  labels:
    app: bccmusic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bccmusic-frontend
  template:
    metadata:
      labels:
        app: bccmusic-frontend
    spec:
      containers:
      - name: bccmusic-frontend
        image: ghcr.io/akkercheval/bccmusic-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi