---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: db-credentials
  namespace: bccmusic-api
spec:
  encryptedData:
    password: AgA44p7mmfPuP6xK8lE9JxDv2rXGEuiE3tSiL/yIFNDHJPw7ztW+Ljz72V+439LB4FQpdvPeYxLpctaDh8rs54TaVc74gdc0APXXR16eBmuYoijF8V+7hnjPlUpBPhOv22VFeUHLNuCYgbGoqC7KVBmmmUp52mFi50wl1q9VZwuxlkRituscrTPILZn2P3qlKV4znyGySv7Sb7Tp159fdO1Y7SgTAOtuN44Q/MkSogifFx8TBmT2utlAqHzfvKeLZCaGNVf3LwgecAUn91ZGtlO500N4znVi9sWjpB+3+r9t9fTtFEy0jwrlPpKe9FIqe1RHZ4stw+N8NdxV4e02YBBKFRPDrYOYBDt7NaCEkOUXaPw9uUtuFF4toLoWcAwCFXKamPgmnkGBm/ns9blmxGIzipGxxgRh+JyhcCgWrmNkeQmMoChFDMc7K65OmuBn2TzHxs2xMqQlnc8tRQ8rg3Bj20i8WkbMVQEIr21c4rqGZSOCgmkC7meAwL6+3qgN2do8PfPhY5nfw13WPgvvlw66L2G+ILSUUpPzRXvmohnNWSJrc/Yp38FTrpgsJ8ZAul2TLC4jjwN1jzZpAN2X/VbD4YycBdTls0SloPTK3Zrxxi5mpiULs3+aKUpWWBwdwn+WA6cj8cVmM8ehouQC8dVg28+4KoJfeA9ACDeSkbo5QXKS4P/Pi/8ixt6KpzkuusUup5NGQGfUNj/ymNLhvVHW/hs=
    username: AgAQh+qS5J1pQ7tbFOLxxTHiivgwdrBGUcIQ+T33s7DH6e7f1YeFkRPdgCVU23TV6ske0n+AoAOVuxq3OMsw+VGN1VXybJQzsfRNgTQmm2ioZNOm6CLZ1cvuOKYjsnwAusyauJB7DyNJZvvhwdOYiEzq4LoEfnQCizlecbY0ykQ43PZSMbZTThmq+KpSbSOc+S3DUAW8tM7EPfJjvItY3ZtHw/rmgQFu+luWleczWO+hGOkWqEvqXWeX6jESoJ3NEa7ioka7uMOYdftjQCPq29NupKViQYt4YKzHTVrIZdZ3yEACJALEnFYObdmhmC4fezrl4KGDKvt+hD4Xi+e0BRiBUYeZDyZNz4T6hQdDOcfrh+KMPIWKpYcd0CYCPSHWylBKrJK7Q6hzq+b/hMj0HqNrYzRKe56D9vq91Uzrx2nXElcL8HWbSD5mqS/b4Rq1zgOq/xL8EQ/NUphgi0nLgXok07Qu8d/4N89XBFkOgTmUt9H9SlNZ2y+eBHxicJqGYK3EsDjJlVtXcSF4rGUHQaPcz1oGrcvNcn9N8B6gO/v07BJx8hkVbqzuZOsY5ssgwMNanx3huqX3wdyTUviWMUbvwEMTqOAm6GygQD3rLSCdI00gPOIDzzIVM+c8nytxAM0hDVHeEtGPROjx2ditHST1nMrGZ7Z4bhNG8G2+/aopoPtHEBkGO+sQVb21sVUhEpqns2v8FAfIHr3+foqS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: db-credentials
      namespace: bccmusic-api
    type: Opaque
