---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: db-credentials
  namespace: bccmusic-api
spec:
  encryptedData:
    password: AgBG0Ri8uhbr8YAJgZmflf2yqpbecBD2gEygXtvMVxaB467fkcBWjYPOF6U5W8IChCXh5988HzTXklztkIp9ELcY/pijOQp7DmzCnbEZ52bKQki8wdC9kEL5ALqAK78g8xuzakQkcAK29GVBbnsaXjPbGUvWf4XSgWNMo1ElW1+UEiBhl96kTKqrMTE2D4YXlItnKCf/8kFFUYiyHA7sroLhLhQeLSS0AWv+D4d/V3sq4iesSabtx8q8cpRVAxCH3UgqlhNkKHopjoPlzifNDa+X3SnXNjd9+UDhQQbuonrm/F9eFig3CUCuvUPqe7KuHOMo8D6YB+Rv9nOAuSlJ6HVPL5Y6X+AralaHKphIq6KEPj3gCQKVQbLX0s6k7VgJ8yf+Jhh7pwokNMnojH+ZGErJaXA1Jkwz8jj+CEFqQwSUT87be0t7jj7vAsyTldnbUvr/uR0SGNgMAV1qzyTBxf/8eMbhOmGQax9/1VnbQWd4Zy9NtMPwHFckkkKUOBTQhJ/VTkgWKUrE9KcRymHlStkk6aGmQQjw6ELpxFmnnQ7FPM/R4VUrsielzBpEFfaE1GkZ2EPHhRT7zWEU6AO7HwUKvCA19ve6wq28dqycztX0qFO1Lch2AOEj29KkJjMuzSx084XF09tH8PkfOpK64vywGP/B/KT/blF55oUJ09+u1zECPM1HIdihH2XNZq6YMxvyRX6W9PeQ7x6zT4S91Ef4UGY=
    username: AgBMIZ4ctK3zoBhrnNOh33j5TsBPexkiYEUqEESanAH4m2NQ9JywXIfHK+xmG1kr6SnW/ogwxK2K7YCqJuRMqvDfy8HZfG5tdscUJ9CPxJkTs6jMWf3/bcus5eEzmNTr66t1+lZhn7zM/b3Ou+wYcNcBfnZLAGDkvGelgjmC//MFBPcL6cfgX1hPrRCCWvThNQUdE9oMks8YpFZGu4lOc30R88LUvZ8SOWja5kzDbfPXxd+tlf3xmXcep/Qo7+5660s8Od0nXPHnJmtS191ZWLidf3Rw4lhoraOofqv3v7iueSnPQd/ZOySEIPNjZply8PZ6wSjB2FfX/QMHb5pZYep0hUt41LwFRGcyqdoCjIMjCJKom+30vh37jGqqrup1VcrsZLO8fiGKtd7Kyg7i2iFTfBPUvYriI2NQ+BRnMd5E+nQPKeHtzGaEugM56+3/NY+2dkGmrUsVjNdjIOvnaC93cCcLq9Rd/ALUUoE5YtI9T0cqr1ApotO2euNRZeQgOQhs7nDYjzLXynZn1CoosEluf4BtsMfhACWodPiMoHPusVfLiCtcAypNaGPStiVjqEsOIiZ9oeSVj2U0ULJKSrbP9mxOTdfZknWMvJgvxPL7J6KqXdz4FgrpezZnzLUAElM6IZVbdqVhq6DQXOsGgfTgh/qJXLhsIKPxu78dfVjUw+MX4Tl2bDdFeHG0dV7qn0+33IoBEp4RVQN7kY3N
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: db-credentials
      namespace: bccmusic-api
    type: Opaque
