---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: db-credentials
  namespace: bccmusic-api
spec:
  encryptedData:
    password: AgCio5tQTcwyiU+IQZzHhjwtGd3ORIkijZNZm7RBuD7lsklswWAt3nco9KKQxXjeJAKEX8oDjpXzSNosrphAo2NYkshxmLsiL4sS6heXni8Hoy4hCzqHbsd9+d+VYQ7XMbFEanaQpV6nqs+kO7YY3IXtAUsyqVqE2GsmLl55d6dp8sYkCxkqzZ0mZIeoxv1NHN+E49OXFuRd/zgwrTeLEcMBtz6/a6RZUJcZoP0tHr0LEWg+xfrUBvkUtAKy2v4Cqa5FNr5q+8MXLABHKmUmB8lvWrPnLSM039vt91rklXYHYeVigSTN5y3R/XXcuNGvIkOOgwHc0RDzu86DyDECQ2ycDnPwDZQlmLYy1b/X/xaghKE5CaSpo/0mavJvkKqRbpif+vy/Q23X3ACVolQCYjcxi5AYOcjD6cokeFWOWRLM03Ptn1dBU4zQ+VL9hITN92E9GvOr3vrAW7+pDtGM66pEwQakO180zgQ3U9wXfFmOEO78bMrdSdTsD4hxKBZQCPePymfS2SxmmAe4gqlkGGzmGXOVx1CUee5x6MV/gHOSWbijP/Jgi5Ylo9ZmfXrTq23TYWROM6LNk49weqN1GTE96Sr1kbnRq+OVR2ufy7ByXphR58+WiAol5sGVu8olu++yqH2mB1WIRxqdehWena4UofOUD1eyKNwfooTZVhJf1UlAO+i3YPT+HX1WhbP/wTK1U8xe5EPwmo4W53a/nDYWY1rNiCM=
    username: AgCk0VkvUfsd8S1rtRQJrLRhjOrunA38EeiODhTixyj2If9RTD+tMjdwQ5tqcGnku6Ik0fiMx0A9iCKQ29vtt3/WkIU/pDGBbdr6xdepGrW6/DFS3F8XzUmJL1Euxll7k4ViqDQ4/E3gybkuO/hC6MhUSm+1+wvilfw+bN2/Bht3U9Fb2tH+cxRkyz5QVOcUr8sVFZ3UygFCVA+GlyX9rthde4LfKFNVfF/YFhgVwcJq32Y+t1+ELo3mcBj2LmRlPR+lRBghf+xfHKGJLCKDy/3cmxPUavxo7hCfeWUE8WzDH82kIZYQfGMTT8paKcWbPUXu1kt28j9phPbx4r0Dhfgc9J8998pQiWZnZZZ0thoYeHasYFoqTawUuRXh4J6EsuRBHva3n0qCxreNa29fwGmBDZCRR4x9XcH1hsmjGGVYHsdJFQat/tPcP8I8ORZPqEFLqn4O21kWPyyh6iNe0A0KWvUAkzB5Td+1RG1BAJJwjBRvy1KTqDUU887RAySxQqsDpboEUZQuoVDWJAuRzce3zXS1G66CcPgEc9PrlUPv+WzuVmD/XGO3s9C8Ca3g4YY1a0TXn99Ahc0KcJaW7zJBLgGQ6TANCeP04iNJqDHYwM6PPKXvRbvkruJzLViCtI9PbEDNFi7OBUkxeIM6o+CiPihjcddH6cbMs17NVIH8Ut0Yk/mxwDUC07SreQuUHud6Mj7y47uM9tmsLdYG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: db-credentials
      namespace: bccmusic-api
    type: Opaque
