apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ws-bccmusic-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Allows clean deletion if needed
spec:
  project: default
  source:
    repoURL: https://github.com/akkercheval/bccmusic-gitops.git
    targetRevision: main
    path: apps/ws-bccmusic-api
  destination:
    server: https://kubernetes.default.svc
    namespace: bccmusic-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Helps with CRDs / complex resources
