apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-bccmusic-api
  namespace: bccmusic-api
  labels:
    app: ws-bccmusic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-bccmusic-api
  template:
    metadata:
      labels:
        app: ws-bccmusic-api
      annotations:
        redeploy: "2026-04-03-v3"
    spec:
      containers:
        - name: backend
          image: ghcr.io/akkercheval/ws-bccmusic-api:sha-782b5e003214ae4538e13918d45251f7556773bf
          imagePullPolicy: Always
            # Auto-updated by CI on 782b5e003214ae4538e13918d45251f7556773bf (build #28)
            # Auto-updated by CI on b90375c3833e1cb9ea08a0ebe88e17f154cfe845 (build #27)
            # Auto-updated by CI on 1b2cf221973a3a399d0659b7f5723e0dd27e9bd7 (build #26)
            # Auto-updated by CI on 630156b29cb519fda2a1a1bf6f7809d9929a840a (build #25)
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 120 # was 10s
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 600 # was 10s
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://192.168.0.10:1433;databaseName=BCCMusic;encrypt=true;trustServerCertificate=true;"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            # === Suppress actuator health-check logging ===
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_ACTUATE
              value: "ERROR"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: "WARN" # catches any request-filter noise
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
